### ISSUE TITLE
install generated headers 

### ISSUE THREAD

**Issue by DerThorsten** [emscripten-forge/pyjs#14]
currently, the cmake install is broken since the autogenerated files are not included @wolfv

**Comment by wolfv** [comment]
Sorry

**Comment by DerThorsten** [comment]
no worries just stumbled over it

**Comment by DerThorsten** [comment]
one thing is a bit annoying:
 https://github.com/emscripten-forge/pyjs/blob/32b68607c85fe3d3efe21d2bf837a4bd9053b9d2/CMakeLists.txt#L24 
 
 https://github.com/emscripten-forge/pyjs/blob/32b68607c85fe3d3efe21d2bf837a4bd9053b9d2/CMakeLists.txt#L60
 
 allows only a flat list of headers. No subdirectories whatsoever
