### ISSUE TITLE
Issue with bundling with Webpack: "package is a reserved identifier"

### ISSUE THREAD

**Issue by trentfridey** [emscripten-forge/pyjs#44]
Hi, I am using empack to pack a Python environment and serve it in the browser, by serving the pyjs runtime (and the rest of my app code) with Webpack. 

Webpack is having an issue with the use of  `package` in `include/pyjs/pre_js/load_pkg.js`[^1] since it is a [future reserved word in Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#future_reserved_words):

![image](https://github.com/emscripten-forge/pyjs/assets/12117783/57f14ef0-3572-4f3e-80c0-85308fe0a918)

I tried using a `babel` plugin that [transforms reserved words](https://babeljs.io/docs/babel-plugin-transform-reserved-words) but it gave me an error that I had difficulty debugging it since the `pyjs_runtime_browser.js` code is a large file.

It seems more efficient to do a find+replace (i.e. replace `package` with `pkg` or similar) for the few spots it is used. I have a fork with the patch if you would like to merge it.

[^1]:  [`fetchAndUntar`](https://github.com/emscripten-forge/pyjs/blob/862cdd78b6a25dd4d159f5cbdaaddcc85d2805ef/include/pyjs/pre_js/load_pkg.js#L98) and [the function](https://github.com/emscripten-forge/pyjs/blob/862cdd78b6a25dd4d159f5cbdaaddcc85d2805ef/include/pyjs/pre_js/load_pkg.js#L114) beneath

**Comment by DerThorsten** [comment]
feel free to open a PR!

**Comment by trentfridey** [comment]
I will try to do so this week

**Comment by DerThorsten** [comment]
thanks for reporting this!

**Comment by trentfridey** [comment]
Ok fix is in https://github.com/emscripten-forge/pyjs/pull/50/

**Comment by DerThorsten** [comment]
thanks and sorry for the long delay
